name: Ofp Decrypter by Area69Labs..

on:
workflow_dispatch:
    inputs:
      ofp_link:
        description: 'ofp link'
        required: true
      ofp_name:
        description: 'name of ofp'
        required: true

env:
  OFP_LINK: ${{ github.event.inputs.ofp_link }}
  OFP_NAME: ${{ github.event.inputs.ofp_name }}
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: CleanUp Enviroment
         run: |
            wget https://raw.githubusercontent.com/Mediatek-leaks/script-personal/main/init.sh
            sudo bash init.sh
            
       - name: Downloading Ofp Now.. 
         run: |
            sudo apt-get install expect -y
            sudo -E apt-get -qq update
            wget $OFP_LINK
             
       - name: Decrypting Ozip Now
         run: |
             sudo -E apt-get -qq update
             sudo pip install docopt
             sudo pip install pycryptodome
             wget https://raw.githubusercontent.com/bkerler/oppo_decrypt/master/ofp_mtk_decrypt.py
             sudo python3 ofp_mtk_decrypt.py $OFP_NAME out
             
       - name: Compress & Upload Decrypted Zip
         run: |
              zip -r9 Decrypted-ofp.zip out
              
       - name: Upload Decrypted Zip
         run: |
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put Decrypted-ofp.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"     
